# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'testmobilecenter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testmobilecenter
  pod 'MobileCenter'

  target 'testmobilecenterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testmobilecenterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
